// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBGKMVg9J_bg8LzV97miIRyckUf8S3V3Q',
    appId: '1:540714660312:web:14d75596b1ea6997dec2ad',
    messagingSenderId: '540714660312',
    projectId: 'social-app-b21ba',
    authDomain: 'social-app-b21ba.firebaseapp.com',
    storageBucket: 'social-app-b21ba.appspot.com',
    measurementId: 'G-9T5LVXW9R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpOrYCZuHw1T12fy9jEszjFU0Mr-28JBc',
    appId: '1:540714660312:android:04cfe292e3f7bb97dec2ad',
    messagingSenderId: '540714660312',
    projectId: 'social-app-b21ba',
    storageBucket: 'social-app-b21ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKwcshHnIAlKpAWvxREJ8Kna7gRKvYEmM',
    appId: '1:540714660312:ios:798a7c09540f4fe4dec2ad',
    messagingSenderId: '540714660312',
    projectId: 'social-app-b21ba',
    storageBucket: 'social-app-b21ba.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKwcshHnIAlKpAWvxREJ8Kna7gRKvYEmM',
    appId: '1:540714660312:ios:7039dfa5f5f12693dec2ad',
    messagingSenderId: '540714660312',
    projectId: 'social-app-b21ba',
    storageBucket: 'social-app-b21ba.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
